# Generated by Django 5.1.4 on 2024-12-18 11:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0002_student_user_alter_student_firstname_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="user",
        ),
    ]
