# Generated by Django 5.1.4 on 2024-12-18 11:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0004_student_age_student_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="age",
            field=models.IntegerField(default=0),
        ),
    ]
