# Generated by Django 5.1.4 on 2024-12-18 11:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0006_remove_student_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="student",
            old_name="FirstName",
            new_name="first_name",
        ),
        migrations.RenameField(
            model_name="student",
            old_name="LastName",
            new_name="last_name",
        ),
    ]
