# Generated by Django 5.1.4 on 2024-12-18 13:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chat", "0007_rename_firstname_student_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="joined_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="phone",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
